export type DocPlatform = 'both' | 'pc' | 'mobile'
export type DocGroup = 'basic' | 'form' | 'data' | 'navigation' | 'feedback' | 'ai' | 'mobile'
export interface DocEntry { slug: string; name: string; title: string; group: DocGroup; platform: DocPlatform }

export const docGroups: { key: DocGroup; zh: string; en: string }[] = [
  { key: 'basic', zh: '基础组件', en: 'Basic' },
  { key: 'form', zh: '表单组件', en: 'Form' },
  { key: 'data', zh: '数据展示', en: 'Data' },
  { key: 'navigation', zh: '导航组件', en: 'Navigation' },
  { key: 'feedback', zh: '反馈组件', en: 'Feedback' },
  { key: 'ai', zh: 'AI 与聊天', en: 'AI & Chat' },
  { key: 'mobile', zh: '移动端组件', en: 'Mobile' },
]

export const componentDocs: DocEntry[] = [
  { slug: 'config-provider', name: 'ConfigProvider', title: '全局配置', group: 'basic', platform: 'both' },
  { slug: 'button', name: 'Button', title: '按钮', group: 'basic', platform: 'both' },
  { slug: 'icon', name: 'Icon', title: '图标', group: 'basic', platform: 'both' },
  { slug: 'space', name: 'Space', title: '间距', group: 'basic', platform: 'both' },
  { slug: 'divider', name: 'Divider', title: '分割线', group: 'basic', platform: 'both' },
  { slug: 'link', name: 'Link', title: '链接', group: 'basic', platform: 'both' },
  { slug: 'typography', name: 'Typography', title: '文字', group: 'basic', platform: 'both' },
  { slug: 'grid', name: 'Grid', title: '栅格', group: 'basic', platform: 'both' },
  { slug: 'layout', name: 'Layout', title: '布局', group: 'basic', platform: 'both' },
  { slug: 'container', name: 'Container', title: '布局容器', group: 'basic', platform: 'both' },
  { slug: 'input', name: 'Input', title: '输入框', group: 'form', platform: 'both' },
  { slug: 'form', name: 'Form', title: '表单', group: 'form', platform: 'both' },
  { slug: 'input-number', name: 'InputNumber', title: '数字输入框', group: 'form', platform: 'both' },
  { slug: 'switch', name: 'Switch', title: '开关', group: 'form', platform: 'both' },
  { slug: 'radio', name: 'Radio', title: '单选框', group: 'form', platform: 'both' },
  { slug: 'checkbox', name: 'Checkbox', title: '多选框', group: 'form', platform: 'both' },
  { slug: 'select', name: 'Select', title: '选择器', group: 'form', platform: 'both' },
  { slug: 'date-picker', name: 'DatePicker', title: '日期选择器', group: 'form', platform: 'both' },
  { slug: 'time-picker', name: 'TimePicker', title: '时间选择器', group: 'form', platform: 'both' },
  { slug: 'slider', name: 'Slider', title: '滑块', group: 'form', platform: 'both' },
  { slug: 'rate', name: 'Rate', title: '评分', group: 'form', platform: 'both' },
  { slug: 'upload', name: 'Upload', title: '上传', group: 'form', platform: 'both' },
  { slug: 'auto-complete', name: 'AutoComplete', title: '自动补全', group: 'form', platform: 'both' },
  { slug: 'cascader', name: 'Cascader', title: '级联选择', group: 'form', platform: 'both' },
  { slug: 'tree-select', name: 'TreeSelect', title: '树形选择', group: 'form', platform: 'both' },
  { slug: 'transfer', name: 'Transfer', title: '穿梭框', group: 'form', platform: 'both' },
  { slug: 'watermark', name: 'Watermark', title: '水印', group: 'data', platform: 'both' },
  { slug: 'table', name: 'Table', title: '表格', group: 'data', platform: 'both' },
  { slug: 'avatar', name: 'Avatar', title: '头像', group: 'data', platform: 'both' },
  { slug: 'collapse', name: 'Collapse', title: '折叠面板', group: 'data', platform: 'both' },
  { slug: 'image', name: 'Image', title: '图片', group: 'data', platform: 'both' },
  { slug: 'card', name: 'Card', title: '卡片', group: 'data', platform: 'both' },
  { slug: 'descriptions', name: 'Descriptions', title: '描述列表', group: 'data', platform: 'both' },
  { slug: 'tree', name: 'Tree', title: '树形控件', group: 'data', platform: 'both' },
  { slug: 'virtual-list', name: 'VirtualList', title: '虚拟列表', group: 'data', platform: 'both' },
  { slug: 'tag', name: 'Tag', title: '标签', group: 'data', platform: 'both' },
  { slug: 'badge', name: 'Badge', title: '徽标', group: 'data', platform: 'both' },
  { slug: 'empty', name: 'Empty', title: '空状态', group: 'data', platform: 'both' },
  { slug: 'skeleton', name: 'Skeleton', title: '骨架屏', group: 'data', platform: 'both' },
  { slug: 'tabs', name: 'Tabs', title: '标签页', group: 'navigation', platform: 'both' },
  { slug: 'pagination', name: 'Pagination', title: '分页', group: 'navigation', platform: 'both' },
  { slug: 'menu', name: 'Menu', title: '菜单', group: 'navigation', platform: 'both' },
  { slug: 'dropdown', name: 'Dropdown', title: '下拉菜单', group: 'navigation', platform: 'both' },
  { slug: 'breadcrumb', name: 'Breadcrumb', title: '面包屑', group: 'navigation', platform: 'both' },
  { slug: 'steps', name: 'Steps', title: '步骤条', group: 'navigation', platform: 'both' },
  { slug: 'loading', name: 'Loading', title: '加载', group: 'feedback', platform: 'both' },
  { slug: 'progress', name: 'Progress', title: '进度条', group: 'feedback', platform: 'both' },
  { slug: 'alert', name: 'Alert', title: '警告', group: 'feedback', platform: 'both' },
  { slug: 'dialog', name: 'Dialog', title: '对话框', group: 'feedback', platform: 'pc' },
  { slug: 'tooltip', name: 'Tooltip', title: '文字提示', group: 'feedback', platform: 'both' },
  { slug: 'popover', name: 'Popover', title: '气泡卡片', group: 'feedback', platform: 'both' },
  { slug: 'drawer', name: 'Drawer', title: '抽屉', group: 'feedback', platform: 'both' },
  { slug: 'message', name: 'Message', title: '消息提示', group: 'feedback', platform: 'both' },
  { slug: 'popup', name: 'Popup', title: '弹出层', group: 'feedback', platform: 'both' },
  { slug: 'notification', name: 'Notification', title: '通知', group: 'feedback', platform: 'both' },
  { slug: 'popconfirm', name: 'Popconfirm', title: '气泡确认框', group: 'feedback', platform: 'both' },
  { slug: 'result', name: 'Result', title: '结果', group: 'feedback', platform: 'both' },
  { slug: 'chat-message', name: 'ChatMessage', title: '聊天消息', group: 'ai', platform: 'both' },
  { slug: 'chat-choice', name: 'ChatChoice', title: '交互选择', group: 'ai', platform: 'both' },
  { slug: 'cell', name: 'Cell', title: '单元格', group: 'mobile', platform: 'mobile' },
  { slug: 'toast', name: 'Toast', title: '轻提示', group: 'mobile', platform: 'mobile' },
  { slug: 'search', name: 'Search', title: '搜索', group: 'mobile', platform: 'mobile' },
  { slug: 'notice-bar', name: 'NoticeBar', title: '通知栏', group: 'mobile', platform: 'mobile' },
  { slug: 'nav-bar', name: 'NavBar', title: '导航栏', group: 'mobile', platform: 'mobile' },
  { slug: 'tabbar', name: 'Tabbar', title: '标签栏', group: 'mobile', platform: 'mobile' },
  { slug: 'action-sheet', name: 'ActionSheet', title: '动作面板', group: 'mobile', platform: 'mobile' },
  { slug: 'modal', name: 'Modal', title: '弹窗', group: 'mobile', platform: 'mobile' },
  { slug: 'picker', name: 'Picker', title: '选择器', group: 'mobile', platform: 'mobile' },
  { slug: 'list', name: 'List', title: '列表', group: 'mobile', platform: 'mobile' },
  { slug: 'pull-refresh', name: 'PullRefresh', title: '下拉刷新', group: 'mobile', platform: 'mobile' },
  { slug: 'swipe', name: 'Swipe', title: '轮播', group: 'mobile', platform: 'mobile' },
  { slug: 'swipe-cell', name: 'SwipeCell', title: '滑动单元格', group: 'mobile', platform: 'mobile' },
  { slug: 'calendar', name: 'Calendar', title: '日历', group: 'mobile', platform: 'mobile' },
  { slug: 'action-bar', name: 'ActionBar', title: '底部操作栏', group: 'mobile', platform: 'mobile' },
]