import type { ComponentReference, row as createRow, text as createText } from './reference'
import { sourceExample } from './example-sources'

export const createExtendedReferences = ({ row, text }: { row: typeof createRow; text: typeof createText }): Record<string, ComponentReference> => {
  const example = (name: string, mobile = false) => [{ title: text('交互示例', 'Interactive Example'), ...sourceExample(name, mobile) }]
  const disabled = row('disabled', 'boolean', 'provider / false', '禁用交互，可继承 ConfigProvider', 'Disable interaction; inherits ConfigProvider')
  const slot = row('default', '-', '-', '自定义内容', 'Custom content')
  const field = [row('size', 'small | default | large', 'provider / default', '尺寸', 'Field size'), row('readonly / clearable', 'boolean', 'false / true', '只读与清空按钮', 'Readonly and clear control'), row('id / name / ariaLabel', 'string', '-', '输入标识与无障碍名称', 'Field identification and accessible name')]
  const floating = row('teleport', 'boolean | string', 'true', '浮层目标；自定义目标需在打开前存在', 'Overlay target; custom targets must exist before opening')
  return {
    menu: {
      description: text('横向或纵向多级菜单，支持受控选中、展开状态与键盘导航。', 'Horizontal or vertical nested menu with controlled selection, expansion and keyboard navigation.'), demo: 'navigation', examples: example('MenuExample'),
      props: [row('modelValue', 'MenuKey | null', 'null', '当前选中键', 'Current selected key'), row('items', 'MenuItemOption[]', '[]', 'key、label、icon、href、disabled、divided、children；键全局唯一', 'Items with globally unique key, label, icon, href, disabled, divided and children'), row('mode', 'vertical | horizontal', 'vertical', '排列方向；横向子菜单自动定位', 'Orientation; horizontal submenus use anchored positioning'), row('openKeys / defaultOpenKeys', 'MenuKey[]', 'internal / []', '受控或初始展开键', 'Controlled or initial open keys'), row('uniqueOpened', 'boolean', 'false', '仅保留一个展开分支', 'Keep one branch open'), row('ariaLabel', 'string', 'locale', '导航名称', 'Navigation accessible name'), disabled], events: [row('update:modelValue', '(key) => void', '-', '选中变化', 'Selection changed'), row('select', '(item, path) => void', '-', '选择叶子菜单并返回键路径', 'Select a leaf and return its key path'), row('update:openKeys / open / close', '(keys) / (key) => void', '-', '展开状态变化', 'Expansion changed')],
    },
    dropdown: {
      description: text('基于菜单的锚定操作列表，支持点击、悬停和键盘打开。', 'Anchored menu commands opened by click, hover or keyboard.'), demo: 'navigation', examples: example('DropdownExample'),
      props: [row('modelValue', 'boolean', 'uncontrolled', '可选受控显示状态', 'Optional controlled visibility'), row('items', 'DropdownItem[]', '[]', '与 MenuItemOption 一致', 'Uses MenuItemOption structure'), row('label', 'string', 'locale', '默认触发按钮文字', 'Default trigger label'), row('trigger', 'click | hover', 'click', '触发方式', 'Trigger mode'), row('hideOnClick', 'boolean', 'true', '选择有效项后关闭', 'Close after selecting an enabled item'), row('placement / width / ariaLabel', 'FloatingPlacement / number | string / string', 'bottom-start / 220 / locale', '位置、宽度与名称', 'Placement, width and accessible name'), floating, disabled], events: [row('update:modelValue / visible-change', '(visible) => void', '-', '显示变化', 'Visibility changed'), row('command', '(key, item) => void', '-', '有效操作触发', 'Enabled command selected')], slots: [row('default', '-', '-', '自定义触发元素', 'Custom trigger')], methods: [row('show / hide', '() => void', '-', '打开或关闭', 'Open or close')],
    },
    breadcrumb: {
      description: text('展示导航层级，支持可点击路径与长路径折叠。', 'Show navigation hierarchy with selectable paths and long-path compression.'), demo: 'navigation', examples: example('BreadcrumbExample'),
      props: [row('items', 'BreadcrumbItem[]', '[]', 'label、href、disabled，最后一项为当前页', 'label, href and disabled; the last item is current'), row('separator', 'string', '/', '路径分隔符', 'Path separator'), row('maxItems', 'number', '0', '至少 3 时折叠中间项，0 不限制', 'Compress at 3 or more; zero disables compression'), row('ariaLabel', 'string', 'locale', '导航名称', 'Navigation accessible name')], events: [row('select', '(item, index) => void', '-', '点击非当前路径项', 'Select a non-current ancestor')], slots: [row('default', '{ item, index }', '-', '自定义路径内容', 'Custom path content'), row('separator', '-', '-', '分隔符', 'Separator')],
    },
    steps: {
      description: text('有序流程展示，支持状态、描述、点击切换和响应式排列。', 'Ordered workflow with statuses, descriptions, selectable steps and responsive layout.'), demo: 'navigation', examples: example('StepsExample'),
      props: [row('active', 'number', '0', 'v-model:active，等于项数时全部完成', 'v-model:active; all complete when equal to item count'), row('items', 'StepItem[]', '[]', 'title、description、icon、status、disabled', 'title, description, icon, status and disabled'), row('direction', 'horizontal | vertical', 'horizontal', '排列方向，小屏水平模式也会纵向排列', 'Direction; horizontal mode stacks on small screens'), row('clickable', 'boolean', 'false', '允许点击切换', 'Allow selection'), row('processStatus', 'wait | process | finish | error', 'process', '当前步骤状态', 'Current step status'), row('ariaLabel', 'string', 'locale', '流程名称', 'Workflow accessible name'), disabled], events: [row('update:active / change', '(index: number) => void', '-', '步骤选择变化', 'Step selected')],
    },
    notification: {
      description: text('支持四角定位、悬停暂停与多实例堆叠的通知。', 'Notifications with four-corner placement, hover pause and stacked method instances.'), demo: 'overlay', examples: example('NotificationExample'),
      props: [row('modelValue', 'boolean', 'false', '模板显示状态', 'Template visibility'), row('title / message', 'string', "''", '标题与纯文本内容', 'Title and plain text'), row('type', 'info | success | warning | error', 'info', '通知类型', 'Notification type'), row('position', 'top-right | top-left | bottom-right | bottom-left', 'top-right', '显示位置', 'Corner placement'), row('duration / offset / zIndex', 'number', '4500 / 16 / 4000', '持续毫秒、边距和层级；duration 0 不自动关闭', 'Duration, offset and layer; zero duration keeps it open'), row('showClose / closeOnClick', 'boolean', 'true / false', '关闭按钮和点击关闭', 'Close control and click dismissal'), row('icon', 'IconName', 'type icon', '状态图标', 'Status icon'), floating],
      events: [row('update:modelValue', '(visible: boolean) => void', '-', '请求关闭', 'Dismissal request'), row('open / opened / close / closed', '() => void', '-', '生命周期', 'Lifecycle'), row('click', '(event: MouseEvent) => void', '-', '内容点击', 'Content clicked')], slots: [slot, row('title / actions', '-', '-', '标题与操作区', 'Title and actions')], methods: [row('Notification.show / info / success / warning / error', '(message | NotificationOptions, appContext?) => NotificationInstance', '-', '创建通知；同容器相同 id 更新现有实例', 'Create a notification; the same target and id updates it'), row('instance.update / close', '(options) / () => void', '-', '更新或关闭单条通知', 'Update or close one instance'), row('Notification.closeAll / clear / destroyAll', '(selector?) => void', '-', '清理指定目标或全部方法通知', 'Dispose method notifications in one target or all targets'), row('options.onClose / onClosed / onClick', 'function', '-', '方法调用回调', 'Method callbacks')],
      note: text('方法调用按目标与位置自动测量和堆叠；模板模式的多条通知可由调用方设置 offset。', 'Method calls measure and stack by target and position. Set offset yourself for multiple template instances.'),
    },
    popconfirm: {
      description: text('轻量操作确认气泡，支持异步确认与可取消任务。', 'Lightweight confirmation popover with asynchronous and cancellable confirmation.'), demo: 'overlay', examples: example('PopconfirmExample'),
      props: [row('modelValue', 'boolean', 'uncontrolled', '可选受控显示', 'Optional controlled visibility'), row('title / message', 'string', "''", '标题和说明', 'Title and message'), row('confirmText / cancelText', 'string', 'locale', '操作文字', 'Action labels'), row('showIcon', 'boolean', 'true', '显示提示图标', 'Show status icon'), row('beforeConfirm', '(signal) => boolean | Promise', '-', '返回 false 保持打开，抛错触发 error；关闭会取消 signal', 'False keeps open; rejection emits error; dismissal aborts signal'), row('allowCancelWhilePending', 'boolean', 'true', '等待确认时允许点击取消', 'Allow the cancel button while pending'), row('placement / width', 'FloatingPlacement / number | string', 'top / 260', '位置和宽度', 'Position and width'), floating, disabled], events: [row('update:modelValue', '(visible) => void', '-', '显示状态', 'Visibility'), row('confirm / cancel', '() => void', '-', '确认通过或主动取消', 'Approved confirmation or explicit cancellation'), row('error', '(error) => void', '-', '异步确认失败', 'Confirmation rejected')], slots: [row('default / reference', '-', '-', '触发元素', 'Trigger element'), row('content', '-', '-', '自定义说明', 'Custom message')],
    },
    result: {
      description: text('展示流程结果、错误或等待状态，并提供后续操作区。', 'Show workflow results, errors or pending states with follow-up actions.'), demo: 'basic', examples: example('ResultExample'),
      props: [row('status', 'success | warning | error | info | 403 | 404 | 500', 'info', '结果类型', 'Result type'), row('title / subtitle', 'string', "''", '标题与补充信息', 'Title and supporting text')], slots: [slot, row('icon / title / subtitle / extra', '-', '-', '图标、标题、副标题与操作', 'Icon, title, subtitle and actions')],
    },
    link: {
      description: text('语义化链接与轻量命令，支持状态颜色、禁用和安全目标地址。', 'Semantic links and lightweight commands with status colors, disabled state and safe URLs.'), demo: 'basic', examples: example('LinkExample'),
      props: [row('href / target', 'string / _self | _blank | _parent | _top', "'' / _self", '链接地址和目标；无 href 时渲染 button', 'URL and target; renders a button without href'), row('type', 'default | primary | success | warning | danger', 'default', '颜色类型', 'Semantic color'), row('underline', 'boolean', 'true', '悬停下划线', 'Underline on hover'), row('icon', 'IconName', '-', '前置图标', 'Leading icon'), disabled], events: [row('click', '(event: MouseEvent) => void', '-', '有效点击', 'Enabled click')], slots: [slot], note: text('仅允许 HTTP、HTTPS、mailto、tel 和相对地址；新窗口链接自动添加 noopener noreferrer。', 'Allows HTTP, HTTPS, mailto, tel and relative URLs. New-window links add noopener noreferrer.'),
    },
    typography: {
      description: text('用于正文、标题、语义文字、截断与复制的轻量文本组件。', 'Text for paragraphs, headings, semantic styles, truncation and copying.'), demo: 'basic', examples: example('TypographyExample'),
      props: [row('as', 'span | p | div | h1-h6', 'span', '语义标签', 'Semantic element'), row('content', 'string', "''", '默认文本，也可使用插槽', 'Text fallback for the slot'), row('type', 'default | secondary | primary | success | warning | danger', 'default', '文字颜色', 'Text color'), row('size', 'number | string', 'inherited', '字号', 'Font size'), row('bold / italic / underline / code / mark', 'boolean', 'false', '文字强调方式', 'Text emphasis'), row('ellipsis / lines', 'boolean / number', 'false / 0', '单行省略或多行行数限制', 'Single-line ellipsis or line clamp'), row('copyable / copyText', 'boolean / string', 'false / slot text', '复制按钮及可选复制内容', 'Copy action and optional override')], events: [row('copy / copy-error', '(text) / (error) => void', '-', '复制完成或浏览器拒绝', 'Copy success or browser rejection')], slots: [slot], note: text('复制依赖安全上下文下的 Clipboard API，失败会触发 copy-error；文字始终作为文本而非 HTML 渲染。', 'Copy uses Clipboard API in a secure context and emits copy-error on failure. Content is rendered as text, not HTML.'),
    },
    grid: {
      description: text('以 CSS Grid 排列内容，提供明确断点与稳定列宽。', 'CSS Grid layout with explicit breakpoints and stable columns.'), demo: 'basic', examples: example('GridExample'),
      props: [row('columns', 'number | GridBreakpoints', '3', '固定列数，或 xs / sm / md / lg / xl 列数', 'Fixed count or xs / sm / md / lg / xl counts'), row('gap', 'number | string | [number, number]', '16', '间距，数组为行和列', 'Gap; array means row and column gap'), row('align / justify', 'start | center | end | stretch', 'stretch', '内容对齐', 'Item alignment'), row('as', 'div | section | ul', 'div', '容器标签', 'Container tag')], slots: [slot], note: text('断点为 xs: 0、sm: 640、md: 768、lg: 1024、xl: 1280px。未设置的断点沿用前一个值，子项可自行设置 grid-column。', 'Breakpoints: xs 0, sm 640, md 768, lg 1024, xl 1280px. Missing values inherit the preceding count. Children may set grid-column.'),
    },
    layout: {
      description: text('可组合的横向或纵向 Flex 布局，支持间距、对齐与换行。', 'Composable horizontal or vertical Flex layout with gap, alignment and wrapping.'), demo: 'basic', examples: example('LayoutExample'),
      props: [row('direction', 'vertical | horizontal', 'vertical', '排列方向', 'Flow direction'), row('gap', 'number | string', '0', '内容间距', 'Item spacing'), row('align', 'stretch | start | center | end | baseline', 'stretch', '交叉轴对齐', 'Cross-axis alignment'), row('justify', 'start | center | end | space-between | space-around | space-evenly', 'start', '主轴分布', 'Main-axis distribution'), row('wrap / reverse', 'boolean', 'false', '换行与反向排列', 'Wrap and reverse flow'), row('as', 'div | section | main | nav', 'div', '容器语义', 'Container semantics')], slots: [slot],
    },
    container: {
      description: text('组合页头、侧栏、正文与页脚，并约束内容宽度。', 'Compose header, aside, content and footer with a constrained content width.'), demo: 'basic', examples: example('ContainerExample'),
      props: [row('maxWidth / fluid', 'number | string / boolean', '1200 / false', '最大宽度与流式模式', 'Maximum width and fluid mode'), row('padding / gap', 'number | string', '24 / 16', '外部内边距与区域间距', 'Container padding and region gap'), row('asideWidth / asidePosition', 'number | string / left | right', '220 / left', '侧栏宽度与位置', 'Aside width and side')], slots: [slot, row('header / aside / footer', '-', '-', '页头、侧栏和页脚', 'Header, aside and footer')], note: text('小于 768px 时侧栏与正文纵向排列。组件不附加导航逻辑或强制卡片样式。', 'Below 768px the aside and main content stack. No navigation logic or card styling is imposed.'),
    },
    image: {
      description: text('稳定尺寸的图片展示，支持懒加载、失败回退与可操作预览。', 'Stable image presentation with lazy loading, error fallback and an interactive viewer.'), demo: 'basic', examples: example('ImageExample'),
      props: [row('src / alt', 'string', "''", '图片地址与替代文字', 'Image source and alternative text'), row('width / height', 'number | string', '100% / 200', '展示尺寸', 'Display dimensions'), row('fit / position', 'object-fit / string', 'cover / center', '填充与对齐', 'Object fit and position'), row('loading', 'lazy | eager', 'lazy', '原生加载策略', 'Native loading strategy'), row('crossorigin / referrerpolicy', 'string', '-', '原生图片请求属性', 'Native image request attributes'), row('preview / previewSrcList / initialIndex', 'boolean / string[] / number', 'false / [] / source index', '启用预览、图片列表和首次索引', 'Enable preview, sources and initial index'), row('previewVisible', 'boolean', 'uncontrolled', '可选 v-model:preview-visible', 'Optional controlled viewer visibility'), row('closeOnClickOverlay / zIndex', 'boolean / number', 'true / auto', '遮罩关闭与层级', 'Overlay dismissal and stacking'), floating, disabled],
      events: [row('load / error / preview-error', '(event: Event) => void', '-', '图片加载结果', 'Image load result'), row('update:previewVisible', '(visible: boolean) => void', '-', '预览状态', 'Viewer state'), row('show / switch', '(index: number) => void', '-', '打开或切换图片', 'Open or switch image'), row('close', '() => void', '-', '关闭预览', 'Close viewer')], slots: [row('placeholder / error', '-', '-', '加载与失败内容', 'Loading and failure content')], methods: [row('showPreview / closePreview', '(index?) / () => void', '-', '管理预览', 'Manage viewer')],
    },
    card: {
      description: text('用于重复实体的卡片，提供媒体、标题、正文和页脚插槽。', 'A card for repeated entities with media, heading, body and footer slots.'), demo: 'basic', examples: example('CardExample'),
      props: [row('header', 'string', "''", '标题', 'Heading'), row('shadow', 'never | hover | always', 'never', '阴影策略', 'Shadow policy'), row('bordered', 'boolean', 'true', '显示边框', 'Show border'), row('padding / bodyStyle', 'number | string / CSSProperties', '20 / -', '正文内边距与样式', 'Body padding and styles'), row('loading', 'boolean', 'false', '展示骨架并保留已挂载正文', 'Show skeleton while retaining body state')], slots: [slot, row('media / header / extra / footer', '-', '-', '媒体、标题、辅助区和页脚', 'Media, heading, extra and footer')],
    },
    descriptions: {
      description: text('语义化键值描述列表，支持列数、跨列、边框与自定义字段。', 'Semantic description list with columns, spans, borders and field slots.'), demo: 'basic', examples: example('DescriptionsExample'),
      props: [row('items', 'DescriptionItem[]', '[]', 'key、label、value、span', 'Items with key, label, value and span'), row('title', 'string', "''", '列表标题', 'List heading'), row('columns / labelWidth', 'number / number | string', '3 / 100', '列数与横向标签宽度', 'Column count and horizontal label width'), row('border / direction', 'boolean / horizontal | vertical', 'false / horizontal', '边框与字段布局', 'Borders and field direction')], slots: [row('title / extra / empty', '-', '-', '标题、辅助内容与空状态', 'Heading, extra and empty state'), row('[key] / label-[key]', '{ item }', '-', '字段值与标签；没有 key 时使用索引', 'Value and label; index is used without a key')],
    },
    tree: {
      description: text('可选择、勾选、过滤与懒加载的树，使用稳定的唯一节点键。', 'Selectable, checkable, filterable and lazy-loaded tree with stable unique keys.'), demo: 'basic', examples: example('TreeExample'),
      props: [row('data', 'TreeNode[]', '[]', 'key、label、children、disabled、isLeaf；键需全树唯一', 'Nodes with globally unique key, label, children, disabled and isLeaf'), row('modelValue', 'TreeKey | null', 'null', '当前选中节点', 'Current selected node'), row('checkedKeys / expandedKeys', 'TreeKey[]', 'internal', '可选受控勾选和展开键', 'Optional controlled checked and expanded keys'), row('defaultExpandedKeys / defaultExpandAll', 'TreeKey[] / boolean', '[] / false', '初始展开状态', 'Initial expansion'), row('showCheckbox / checkStrictly', 'boolean', 'false / false', '显示勾选与父子独立模式', 'Checkboxes and independent checking'), row('filter / filterNodeMethod', 'string / (query, node) => boolean', "'' / label includes", '过滤并保留匹配节点的祖先', 'Filter while retaining matched ancestors'), row('load', '(node, signal) => Promise<TreeNode[]>', '-', '异步子节点；叶子应设 isLeaf: true', 'Load children; declare leaves with isLeaf: true'), row('indent / expandOnClickNode', 'number / boolean', '20 / false', '缩进与点击展开', 'Indent and expand-on-click'), row('emptyText / ariaLabel', 'string', 'locale', '空状态与树名称', 'Empty text and accessible name'), disabled],
      events: [row('update:modelValue / node-click', '(key) / (node) => void', '-', '选中节点', 'Node selection'), row('update:checkedKeys / update:expandedKeys', '(keys) => void', '-', '状态更新', 'State update'), row('check', '(TreeCheck, node) => void', '-', '完整与半选键、节点', 'Checked and half-checked keys and nodes'), row('expand', '(node, expanded) => void', '-', '展开变化', 'Expansion changed'), row('load / error', '(node, children) / (error, node)', '-', '懒加载结果', 'Lazy-load result')], slots: [row('default', '{ node, expanded, checked }', '-', '节点内容', 'Node content'), row('empty', '-', '-', '空状态', 'Empty state')], methods: [row('getChecked / getNode / setCheckedKeys', '() / (key) / (keys)', '-', '读取或更新树状态', 'Read or update tree state')],
    },
    'virtual-list': {
      description: text('基于 TanStack Virtual 的视口渲染，支持定高、动态测量和索引定位。', 'TanStack Virtual viewport rendering with fixed sizes, dynamic measurement and indexed scrolling.'), demo: 'basic', examples: example('VirtualListExample'),
      props: [row('items', 'Item[]', '[]', '原始数据，插槽保留泛型类型', 'Items with generic slot typing'), row('height / itemHeight', 'number | string / number', '320 / 44', '容器高度与条目高度估计，px', 'Viewport height and estimated row size'), row('itemKey', 'keyof Item | (item, index) => string | number', 'index', '稳定唯一键；数据重排时必须指定', 'Stable key; provide it for reordered data'), row('overscan', 'number', '5', '视口两侧额外渲染数量', 'Extra rendered rows on each side'), row('dynamic', 'boolean', 'false', '通过 ResizeObserver 测量实际条目高度', 'Measure actual row heights'), row('ariaLabel', 'string', 'locale', '列表名称', 'Accessible list name')],
      events: [row('scroll', '(event: Event) => void', '-', '原生滚动', 'Native scroll'), row('range-change', '({ start, end }) => void', '-', '可见索引变化', 'Visible indices changed')], slots: [row('default', '{ item, index }', '-', '每条数据的内容', 'Row content'), row('empty', '-', '-', '空数据内容', 'Empty content')], methods: [row('scrollToIndex', '(index, { align?, behavior? }?) => void', '-', '定位指定项；动态测量使用即时滚动', 'Scroll to an item; dynamic mode uses immediate scrolling'), row('scrollToOffset / measure', '(offset) / () => void', '-', '定位偏移或重新测量', 'Scroll to offset or remeasure')],
    },
    upload: {
      description: text('文件选择、拖放和上传管理，提供进度、取消、重试与异步校验。', 'File selection, drop and upload management with progress, cancellation, retry and async guards.'), demo: 'form', examples: example('UploadExample'),
      props: [row('fileList', 'UploadFile[]', '[]', '支持 v-model:file-list，包含 uid、name、size、status、percentage、raw、url', 'v-model:file-list with uid, name, size, status, percentage, raw and url'), row('action / method / name', 'string / POST | PUT | PATCH / string', "'' / POST / file", 'HTTP 地址、方法和 multipart 文件字段', 'HTTP endpoint, method and multipart field'), row('headers / data / withCredentials', 'object / object / boolean', '{} / {} / false', '请求头、附加表单字段和凭据开关', 'Request headers, extra form fields and credentials'), row('multiple / accept / limit / maxSize', 'boolean / string / number / number', 'false / empty / 0 / Infinity', '多选、类型、最大数量与字节数；limit 0 不限制', 'Multiple selection, accepted types, count and byte limits; zero count is unlimited'), row('autoUpload / drag / showFileList', 'boolean', 'true / false / true', '自动发送、拖放和文件列表', 'Automatic requests, drag-and-drop and file list'), row('listType', 'text | picture', 'text', '文件列表外观', 'File list presentation'), row('beforeUpload', '(file) => boolean | Blob | Promise', '-', '返回 false 阻止上传，返回 Blob 替换请求数据', 'Return false to stop; return Blob to transform the upload'), row('beforeRemove', '(file) => boolean | Promise', '-', '移除拦截', 'Removal guard'), row('httpRequest', '(options: UploadRequestOptions) => Promise<unknown>', 'XHR', '自定义请求，接收 signal 与 onProgress', 'Custom request with signal and onProgress'), disabled],
      events: [row('update:fileList', '(files) => void', '-', '文件状态变化', 'File list state changed'), row('change / remove', '(file, files) => void', '-', '文件变更或移除', 'File changed or removed'), row('progress', '(percentage, file) => void', '-', '上传进度', 'Upload progress'), row('success / error', '(response | error, file) => void', '-', '请求结果', 'Request result'), row('preview / abort', '(file) => void', '-', '预览或取消', 'Preview or cancellation'), row('reject', '(file, type | size | hook) => void', '-', '文件被拒绝', 'File rejected'), row('exceed', '(files, current) => void', '-', '超过数量限制', 'Count limit exceeded')], slots: [row('trigger / tip', '-', '-', '选择按钮和限制说明', 'Trigger and constraints')], methods: [row('submit / abort / remove / clearFiles / addFiles', '() / (uid?) / (uid) / () / (File[])', '-', '发送待处理文件、取消、移除、清空或添加文件', 'Submit pending files, abort, remove, clear or add files')],
      note: text('此示例仅模拟上传进度，不发送文件。生产环境需配置 action 或 httpRequest；自定义请求应监听 AbortSignal。客户端校验不能替代服务端文件校验。', 'This example simulates progress without sending files. Configure action or httpRequest in production and honor AbortSignal. Client-side checks do not replace server validation.'),
    },
    'auto-complete': {
      description: text('本地或异步建议输入，处理输入法、请求取消与过期结果。', 'Local or asynchronous suggestions with IME, cancellation and stale-result protection.'), demo: 'form', examples: example('AutoCompleteExample'),
      props: [row('modelValue', 'string', "''", '输入值', 'Input value'), row('options', 'AutoCompleteOption[]', '[]', '本地建议，value、label、disabled', 'Local suggestions with value, label and disabled'), row('fetchSuggestions', '(query, signal) => options | Promise<options>', '-', '异步建议提供器，替代本地过滤', 'Async provider replacing local filtering'), row('debounce', 'number', '150', '远程查询防抖毫秒', 'Remote debounce in milliseconds'), row('showOnFocus / highlightFirstItem', 'boolean', 'true / false', '聚焦查询与首项高亮', 'Query on focus and initial highlight'), row('placeholder / width', 'string / number | string', "'' / 320px", '输入提示和建议面板宽度', 'Placeholder and popup width'), ...field, floating, disabled],
      events: [row('update:modelValue / input / change', '(value: string) => void', '-', '输入、失焦或选中值变化', 'Input, blur or committed changes'), row('select', '(option: AutoCompleteOption) => void', '-', '选中有效建议', 'Enabled suggestion selected'), row('clear / focus / blur / error', '() / (FocusEvent) / (error)', '-', '清空、焦点与查询错误', 'Clear, focus and query errors')], slots: [row('default', '{ option, index }', '-', '建议内容', 'Suggestion content'), row('empty', '-', '-', '空结果内容', 'Empty result content')], methods: [row('focus / blur / close', '() => void', '-', '管理焦点与面板', 'Manage focus and popup')],
      note: text('示例通过本地延迟模拟异步搜索，没有网络请求；自定义提供器的拒绝与取消均由组件处理。', 'The example simulates asynchronous search locally. The component handles provider rejection and cancellation.'),
    },
    cascader: {
      description: text('逐级选择或搜索完整路径，支持禁用节点与选择分组。', 'Choose through columns or search full paths, with disabled nodes and optional parent selection.'), demo: 'form', examples: example('CascaderExample'),
      props: [row('modelValue', 'CascaderValue', 'null', '路径数组或末级单值', 'Path array or terminal value'), row('options', 'CascaderOption[]', '[]', 'value、label、disabled、children', 'Options with value, label, disabled and children'), row('emitPath / changeOnSelect / filterable', 'boolean', 'true / false / false', '输出完整路径、允许父级选择和搜索', 'Emit paths, permit parent selection and search'), row('separator / placeholder', 'string', "' / ' / locale", '路径分隔符与提示', 'Path separator and placeholder'), ...field, floating, disabled],
      events: [row('update:modelValue', '(value) => void', '-', '选择值变化', 'Value changed'), row('change', '(value, path: CascaderOption[]) => void', '-', '返回值与完整节点路径', 'Return value and full option path'), row('clear', '() => void', '-', '清空', 'Cleared')], slots: [row('default', '{ option }', '-', '自定义列选项', 'Custom column option')], methods: [row('focus / clear', '() => void', '-', '聚焦或清空', 'Focus or clear')],
    },
    'tree-select': {
      description: text('结合树与输入框的单选、多选控件，支持过滤和懒加载。', 'Tree input with single or multiple selection, filtering and lazy loading.'), demo: 'form', examples: example('TreeSelectExample'),
      props: [row('modelValue', 'TreeKey | TreeKey[] | null', 'null / []', '单选键或多选勾选键集合', 'Single key or multiple checked keys'), row('data', 'TreeNode[]', '[]', 'key、label、disabled、children、isLeaf', 'Tree nodes with stable keys'), row('multiple / checkStrictly', 'boolean', 'false / false', '多选和父子独立勾选', 'Multiple selection and independent checking'), row('leafOnly', 'boolean', 'false', '单选时只允许叶子节点', 'Only allow leaves in single mode'), row('filterable / defaultExpandAll', 'boolean', 'false', '搜索与初始展开', 'Search and initial expansion'), row('load', '(node, signal) => Promise<TreeNode[]>', '-', '懒加载子节点', 'Load children lazily'), row('placeholder / width', 'string / number | string', 'locale / 320px', '提示和面板宽度', 'Placeholder and panel width'), ...field, floating, disabled],
      events: [row('update:modelValue / change', '(value: TreeSelectValue) => void', '-', '选择变化', 'Selection changed'), row('clear', '() => void', '-', '清空', 'Cleared'), row('error', '(error, node) => void', '-', '懒加载失败', 'Lazy-load error')], slots: [row('default', '{ node }', '-', '自定义节点内容', 'Custom node content')], methods: [row('focus / clear', '() => void', '-', '聚焦或清空', 'Focus or clear')],
      note: text('多选默认级联，绑定值包含完整勾选节点（含父节点）。checkStrictly 可改为父子独立。', 'Multiple mode cascades by default and returns all checked keys, including parents. checkStrictly makes nodes independent.'),
    },
    transfer: {
      description: text('在两个列表间移动选择项，支持过滤、批量选择与禁用。', 'Move selected entries between two lists with filtering, select-all and disabled items.'), demo: 'form', examples: example('TransferExample'),
      props: [row('modelValue', 'TransferKey[]', '[]', '右侧列表键集合', 'Keys in the target list'), row('data', 'TransferItem[]', '[]', 'key、label、disabled', 'Items with key, label and disabled'), row('titles', '[string, string]', 'locale', '两侧标题', 'Panel titles'), row('filterable / filterPlaceholder', 'boolean / string', 'false / locale', '搜索开关与提示', 'Search control and placeholder'), row('filterMethod', '(query, item) => boolean', '-', '自定义过滤', 'Custom filter'), disabled],
      events: [row('update:modelValue', '(keys) => void', '-', '目标键更新', 'Target keys changed'), row('change', '(keys, left | right, movedKeys) => void', '-', '移动方向与本次移动键', 'Direction and moved keys'), row('check-change', '(keys) => void', '-', '勾选变化', 'Checked keys changed')], slots: [row('default', '{ item }', '-', '列表项', 'List item'), row('left-footer / right-footer', '-', '-', '两侧底部', 'Panel footers')], methods: [row('clearQuery', '(left | right) => void', '-', '清空指定侧搜索', 'Clear one panel query')],
    },
    'date-picker': {
      description: text('日期和日期范围选择，复用 Calendar 的边界、禁用日期与键盘行为。', 'Date and range input sharing Calendar bounds, disabled dates and keyboard behavior.'), demo: 'form', examples: example('DatePickerExample'),
      props: [row('modelValue', 'DatePickerValue', "'' / []", '单日期字符串或起止日期数组，格式 YYYY-MM-DD', 'Date string or range array in YYYY-MM-DD'), row('type', 'date | daterange', 'date', '选择模式', 'Selection mode'), row('format', 'string', 'yyyy-MM-dd', 'date-fns 展示格式；不改变绑定值格式', 'date-fns display format; model format is unchanged'), row('minDate / maxDate / disabledDate', 'string / string / (Date) => boolean', '-', '日期边界和禁用规则', 'Bounds and disabled-date predicate'), row('firstDayOfWeek / maxRange', '0-6 / number', '1 / -', '周首日与范围最大天数', 'Week start and maximum inclusive range'), row('placeholder', 'string', 'locale', '未选择时的提示', 'Empty field placeholder'), ...field, floating, disabled],
      events: [row('update:modelValue / change', '(value: DatePickerValue) => void', '-', '日期变化', 'Date changed'), row('clear', '() => void', '-', '清空值', 'Value cleared'), row('visible-change', '(opened: boolean) => void', '-', '浮层变化', 'Popup visibility'), row('invalid', '(disabled | max-range) => void', '-', '范围被拒绝', 'Rejected range')], methods: [row('focus / show / hide', '() => void', '-', '控制焦点或浮层', 'Manage focus and popup')],
    },
    'time-picker': {
      description: text('基于原生时间输入的单值或区间选择，支持秒、边界与跨日设置。', 'Native time input for single values or ranges, with seconds, bounds and overnight policy.'), demo: 'form', examples: example('TimePickerExample'),
      props: [row('modelValue', 'TimePickerValue', "'' / ['', '']", 'HH:mm 或 HH:mm:ss 字符串，区间使用数组', 'HH:mm or HH:mm:ss; array for ranges'), row('isRange / seconds', 'boolean', 'false', '区间选择与秒输入', 'Range and seconds input'), row('min / max', 'string', "''", '可选择的时间边界', 'Selectable time bounds'), row('step', 'number', '60 / seconds: 1', '原生时间步长，单位秒', 'Native step in seconds'), row('allowOvernight', 'boolean', 'false', '允许结束时间早于开始时间', 'Allow end before start'), row('disabledTime', '(value: string) => boolean', '-', '自定义禁用时间', 'Custom disabled-time predicate'), ...field, disabled],
      events: [row('update:modelValue / change', '(value: TimePickerValue) => void', '-', '有效值变化', 'Valid value changed'), row('invalid', '(value: string) => void', '-', '无效输入被还原', 'Rejected input is restored'), row('clear / focus / blur', '() / (FocusEvent) => void', '-', '清空与焦点事件', 'Clear and focus events')], methods: [row('focus / blur / clear', '(index?) / () => void', '-', '操作原生输入', 'Control native inputs')],
      note: text('时间编辑界面由浏览器与操作系统提供，桌面和手机外观可能不同。不解析自由格式自然语言时间。', 'The browser and operating system supply the editor, so desktop and mobile appearance may differ. Free-form natural-language time parsing is not provided.'),
    },
    slider: {
      description: text('数值和有序区间滑块，支持小数步进、标记与原生键盘操作。', 'Single and ordered-range sliders with decimal steps, marks and native keyboard support.'), demo: 'form', examples: example('SliderExample'),
      props: [row('modelValue', 'number | [number, number]', 'min / [min, max]', '数值或有序区间', 'Value or ordered range'), row('min / max / step', 'number', '0 / 100 / 1', '边界和步进，小数会规范化', 'Bounds and normalized decimal steps'), row('range', 'boolean', 'false', '双滑柄区间选择', 'Two-thumb range selection'), row('vertical / height', 'boolean / number', 'false / 180', '垂直模式与高度', 'Vertical mode and height'), row('showValue / format', 'boolean / (number) => string', 'true / String', '数值展示和格式', 'Value output and formatting'), row('marks', 'Record<number, string>', '-', '刻度标记', 'Track marks'), row('ariaLabel', 'string', 'locale', '滑块名称', 'Accessible name'), disabled], events: [row('update:modelValue / input', '(value: SliderValue) => void', '-', '拖动中的值', 'Value while dragging'), row('change', '(value: SliderValue) => void', '-', '提交交互后的值', 'Committed interaction value')],
    },
    rate: {
      description: text('支持半星、清空与只读展示的评分控件。', 'Rating with half steps, clearing and readonly display.'), demo: 'form', examples: example('RateExample'),
      props: [row('modelValue', 'number', '0', '评分值', 'Rating value'), row('max', 'number', '5', '星数，1 至 20', 'Star count from 1 to 20'), row('allowHalf / clearable / readonly', 'boolean', 'false / true / false', '半星、再次点击清空与只读', 'Half steps, repeated-click clearing and readonly state'), row('size / color', 'number / string', '24 / warning token', '图标尺寸与颜色', 'Icon size and color'), row('showText / texts', 'boolean / string[]', 'false / []', '评分文字', 'Rating labels'), row('ariaLabel', 'string', 'locale', '评分名称', 'Accessible name'), disabled], events: [row('update:modelValue / change', '(value: number) => void', '-', '评分变化', 'Rating changed'), row('hover-change', '(value: number) => void', '-', '预览评分变化', 'Hovered rating changed')],
    },
    swipe: {
      description: text('基于 Embla 的触摸轮播，支持循环、自动播放和键盘导航。', 'Embla-powered touch carousel with looping, autoplay and keyboard navigation.'), demo: 'mobile', examples: example('SwipeExample', true),
      props: [row('modelValue', 'number', '0', '当前索引，从 0 开始', 'Current zero-based slide index'), row('items', 'SwipeItem[]', '[]', '每项包含 key、src、alt，可携带自定义数据', 'Items with key, src, alt and optional custom data'), row('loop', 'boolean', 'true', '循环播放，布局不足以循环时由引擎回退', 'Loop when the layout supports it'), row('autoplay', 'number', '0', '间隔毫秒，0 禁用；减少动画或隐藏页面时暂停', 'Interval in milliseconds; zero disables it; pauses for reduced motion or hidden pages'), row('pauseOnHover', 'boolean', 'true', '悬停暂停；焦点与拖动也会暂停', 'Pause on hover, focus and drag'), row('showIndicators / showArrows', 'boolean', 'true / false', '指示器与箭头', 'Indicators and arrows'), row('height', 'number | string', '180', '稳定展示高度', 'Stable viewport height'), row('ariaLabel', 'string', 'locale', '轮播名称', 'Accessible carousel name'), disabled],
      events: [row('update:modelValue / change', '(index: number) => void', '-', '活动页变化', 'Active slide changed')], slots: [row('default', '{ item, index, active }', '-', '自定义每页内容，默认显示图片', 'Custom slide content; defaults to an image')], methods: [row('prev / next / swipeTo', '() / (index) => void', '-', '前后切换或指定索引', 'Navigate slides')],
    },
    'swipe-cell': {
      description: text('向两侧滑动以显示操作，保留纵向滚动和异步关闭拦截。', 'Reveal actions on either side while retaining vertical scrolling and asynchronous close guards.'), demo: 'mobile', examples: example('SwipeCellExample', true),
      props: [row('modelValue', "'' | left | right", "''", '展开位置，可选受控状态', 'Optional controlled reveal position'), row('leftWidth / rightWidth', 'number', 'auto', '覆盖操作区域的测量宽度', 'Override measured action widths'), row('beforeClose', '(context: SwipeCellClose) => boolean | Promise', '-', '返回 false 阻止关闭；context 包含 position、reason', 'Return false to keep open; receives position and reason'), row('ariaLabel', 'string', "''", '滑动内容的键盘名称', 'Accessible name for keyboard interaction'), disabled],
      events: [row('update:modelValue / open', '(position) => void', '-', '展开位置变化', 'Reveal position changed'), row('close', '(context) => void', '-', '通过拦截后关闭', 'Closed after guard approval'), row('click', '(left | right | cell) => void', '-', '操作区或内容点击', 'Action or content clicked'), row('error', '(error) => void', '-', '关闭拦截失败', 'Close guard rejected')], slots: [slot, row('left / right', '-', '-', '两侧操作按钮', 'Side action buttons')], methods: [row('open / close', '(position) / () => Promise<void>', '-', '手动展开或请求关闭', 'Reveal or request dismissal')],
    },
    calendar: {
      description: text('支持单选、多选和范围的日历，日期使用无时区的 YYYY-MM-DD。', 'Single, multiple and range calendar using timezone-free YYYY-MM-DD values.'), demo: 'mobile', examples: example('CalendarExample', true),
      props: [row('modelValue', 'string | string[]', "'' / []", '选择值，范围包含起止日期', 'Selected date or dates; range contains start and end'), row('type', 'single | multiple | range', 'single', '选择模式', 'Selection mode'), row('month', 'string', 'selection / today', '可选 v-model:month，格式 YYYY-MM', 'Optional v-model:month in YYYY-MM'), row('minDate / maxDate', 'string', '-', '含边界的日期范围', 'Inclusive date bounds'), row('disabledDate', '(date: Date) => boolean', '-', '禁用日期；范围不能穿过禁用日', 'Disable dates; ranges cannot cross disabled days'), row('firstDayOfWeek', '0-6', '1', '每周首日，0 为星期日', 'Week start; zero is Sunday'), row('maxRange', 'number', '-', '范围最大天数，含首尾', 'Maximum range length including endpoints'), row('showConfirm / confirmText', 'boolean / string', 'false / locale', '确认操作', 'Confirmation action'), disabled],
      events: [row('update:modelValue / change / confirm', '(value: CalendarValue) => void', '-', '值变化或确认', 'Value changed or confirmed'), row('select', '(date: string) => void', '-', '点击有效日期', 'A valid date was selected'), row('update:month / panel-change', '(month: string) => void', '-', '当前月份变化', 'Displayed month changed'), row('invalid', '(disabled | max-range) => void', '-', '范围无效', 'Invalid range')], slots: [row('day', '{ date, selected }', '-', '自定义日期单元', 'Custom day cell')], methods: [row('goToday', '() => void', '-', '定位到今天', 'Display today')],
    },
    'action-bar': {
      description: text('移动页面底部操作栏，支持图标、徽标、安全区与固定定位。', 'Mobile action bar with icons, badges, safe-area padding and fixed positioning.'), demo: 'mobile', examples: example('ActionBarExample', true),
      props: [row('actions', 'ActionBarItem[]', '[]', 'key、label、icon、type、badge、disabled、loading', 'Items with key, label, icon, type, badge, disabled and loading'), row('fixed', 'boolean', 'false', '固定到底部，并保留占位高度', 'Fix to the bottom and reserve layout space'), row('safeArea', 'boolean', 'true', '底部安全区', 'Respect bottom safe area'), row('ariaLabel', 'string', 'locale', '工具栏名称', 'Toolbar accessible name'), disabled], events: [row('click', '(action: ActionBarItem) => void', '-', '可用操作被点击', 'Enabled action clicked')], slots: [row('default', '-', '-', '替换默认操作按钮', 'Replace generated buttons')],
      note: text('商品示例仅更新本地收藏、购物车数量和订单状态，不创建真实交易。固定位置受手机预览容器约束。', 'The product example updates local favorite, cart and order state only; it creates no transaction. The fixed bar remains inside the phone preview.'),
    },
    picker: {
      description: text('移动端多列与级联选择器，支持确认、取消和键盘操作。', 'Mobile independent or cascading columns with confirmation, cancellation and keyboard navigation.'), demo: 'mobile', examples: example('PickerExample', true),
      props: [row('modelValue', 'PickerValue[]', '[]', '每一列的选中值，确认前可用独立草稿', 'Selected value per column; use a draft before confirmation'), row('columns', 'PickerOption[] | PickerOption[][]', '[]', '单列、级联 children 或独立多列；选项包含 label、value、disabled', 'Single/cascading options or independent columns; label, value and disabled'), row('title', 'string', "''", '工具栏标题', 'Toolbar title'), row('showToolbar', 'boolean', 'true', '显示确认与取消', 'Show confirm and cancel'), row('loading', 'boolean', 'false', '加载状态', 'Loading state'), row('confirmText / cancelText', 'string', 'locale', '操作文字', 'Action labels'), disabled],
      events: [row('update:modelValue', '(values) => void', '-', '选项变化时更新数组', 'Update selected values'), row('change / confirm', '(selection: PickerSelection) => void', '-', '返回 values 和 options', 'Return values and options'), row('cancel', '() => void', '-', '取消选择', 'Cancel selection')], slots: [row('option', '{ option, columnIndex }', '-', '自定义选项', 'Custom option')], methods: [row('confirm / getSelected', '() => void / PickerSelection', '-', '确认或读取当前有效选项', 'Confirm or read current valid selection')],
      note: text('Picker 本身不创建弹层。示例在手机内用 Drawer 展示；禁用或无效的子级值会回退到第一项可选值。', 'Picker is inline. This example composes a Drawer inside the phone. Invalid descendants fall back to the first enabled option.'),
    },
    list: {
      description: text('滚动接近底部时加载更多，支持错误重试和结束状态。', 'Load more near the scroll boundary with explicit retry and completion states.'), demo: 'mobile', examples: example('ListExample', true),
      props: [row('loading', 'boolean', 'false', '用 v-model:loading 控制加载，完成后设为 false', 'Control with v-model:loading; reset after completing a request'), row('finished / error', 'boolean', 'false', '结束标记与失败状态；error 支持 v-model:error', 'Finished and failed states; error supports v-model:error'), row('offset', 'number', '100', '距滚动容器底部的触发距离，px', 'Distance from scroll boundary in pixels'), row('immediateCheck', 'boolean', 'true', '挂载后检查是否需要首批数据', 'Check after mount'), row('loadingText / finishedText / errorText', 'string', 'locale', '各状态文案', 'Status labels'), disabled],
      events: [row('load', '() => void', '-', '请求下一批，完成前不会重复触发', 'Request the next batch once per loading cycle'), row('update:loading / update:error', '(value: boolean) => void', '-', '加载与重试状态', 'Loading and retry state')], slots: [slot, row('loading / finished / error', '-', '-', '自定义状态内容', 'Custom status content')], methods: [row('check', '() => void', '-', '容器尺寸或可见性变化后手动检查', 'Manually check after size or visibility changes')],
      note: text('示例使用本地计时器分页，不发送网络请求。离线状态下下一次加载会失败，恢复在线后可重试。实际项目请在请求结束后更新 loading、error 与 finished。', 'The example paginates locally without network requests. Offline mode makes the next request fail. In production update loading, error and finished when your request settles.'),
    },
    'pull-refresh': {
      description: text('滚动容器顶部的下拉刷新，支持触摸手势和键盘刷新。', 'Pull to refresh at the top of a scroll container, with a keyboard-accessible refresh action.'), demo: 'mobile', examples: example('PullRefreshExample', true),
      props: [row('modelValue', 'boolean', 'false', '刷新中状态，任务结束后设为 false', 'Refreshing state; reset after the task'), row('headHeight / pullDistance', 'number', '56 / 64', '指示器高度与触发距离，px', 'Indicator height and trigger distance in pixels'), row('pullingText / loosingText / loadingText', 'string', 'locale', '下拉、释放与加载文案', 'Pull, release and loading labels'), disabled],
      events: [row('update:modelValue', '(value: boolean) => void', '-', '触发刷新时返回 true', 'Emit true when refresh begins'), row('refresh', '() => void', '-', '执行刷新任务', 'Run the refresh task'), row('change', '({ status, distance }) => void', '-', '拖动状态变化', 'Gesture progress')], slots: [slot, row('head', '{ status, distance }', '-', '自定义指示器', 'Custom indicator')], methods: [row('refresh', '() => void', '-', '手动请求刷新，加载中会忽略重复调用', 'Trigger refresh; ignore duplicate pending calls')],
    },
  }
}